---
- hosts: kubernetes-worker-nodes
  vars_files:
  - env_variables
  tasks:
  - name: Copying token to worker nodes
    copy: src={{ token_file }} dest=join_token

  - name: Joining worker nodes with kubernetes master
    shell: |
     kubeadm reset
     cat join_token | tail -2 > out.sh
     chmod 755 out.sh
     sh out.sh
